apiVersion : apps/v1
kind: Deployment
metadata:
  name: hemanthrevhirebackend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hemanthrevhirebackend
  template:
    metadata:
      labels:
        app: hemanthrevhirebackend 
    spec:
      containers:
        - name: hemanthrevhirebackend 
          image: revhireacr.azurecr.io/hemanthrevhirebackend
          env:
          - name : DB_URL
            valueFrom: 
              secretKeyRef:
                name: db-credentials
                key: DB_URL
          - name : DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key : DB_USERNAME
          - name : DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PORT
